2021-02-17 19:27:17,935 INFO    MainThread:234159 [wandb_setup.py:_flush():70] setting env: {}
2021-02-17 19:27:17,936 INFO    MainThread:234159 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-17 19:27:17,936 INFO    MainThread:234159 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-17 19:27:17,936 INFO    MainThread:234159 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-17 19:27:17,936 INFO    MainThread:234159 [wandb_init.py:_log_setup():303] Logging user logs to /home/tyna/Documents/safe-experts/algos/wandb/run-20210217_192717-2s0u30ok/logs/debug.log
2021-02-17 19:27:17,936 INFO    MainThread:234159 [wandb_init.py:_log_setup():304] Logging internal logs to /home/tyna/Documents/safe-experts/algos/wandb/run-20210217_192717-2s0u30ok/logs/debug-internal.log
2021-02-17 19:27:18,287 WARNING MainThread:234159 [wandb_init.py:init():595] interrupted
Traceback (most recent call last):
  File "/home/tyna/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/home/tyna/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 400, in init
    ret = backend.interface.communicate_check_version(
  File "/home/tyna/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 615, in communicate_check_version
    result = self._communicate(rec)
  File "/home/tyna/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 447, in _communicate
    return future.get(timeout)
  File "/home/tyna/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 63, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2021-02-17 19:27:18,293 INFO    MainThread:234159 [internal.py:handle_exit():138] Internal process exited
